var definitions = {
  "manuscripts" : [
    "void",
    "Harleianus 5596",
    "Gennadianus 45",
    "Atheniensis"
  ],
  "moon" : {
    "phase" : {
      "symbol" : [
        "void",
        "🌑",
        "🌒",
        "🌓",
        "🌔",
        "🌕",
        "🌖",
        "🌗",
        "🌘"
      ],
      "name" : [
        "void",
        "new",
        "waxing crescent",
        "first quarter",
        "waxing gibbous",
        "full",
        "waning gibbous",
        "last quarter",
        "waning crescent"
      ]
    },
    "mansion" : {
      "tropical" : [
        "void",
        "12 Aries 51",
        "25 Aries 42",
        "8 Taurus 34",
        "21 Taurus 25",
        "4 Gemini 17",
        "17 Gemini 8",
        "0 Cancer 0",
        "12 Cancer 51",
        "25 Cancer 42",
        "8 Leo 34",
        "21 Leo 25",
        "4 Virgo 17",
        "17 Virgo 8",
        "0 Libra 0",
        "12 Libra 51",
        "25 Libra 42",
        "8 Scorpio 34",
        "21 Scorpio 25",
        "4 Sagittarius 17",
        "17 Sagittarius 8",
        "0 Capricorn 0",
        "12 Capricorn 51",
        "25 Capricorn 42",
        "8 Aquarius 34",
        "21 Aquarius 25",
        "4 Pisces 17",
        "17 Pisces 8",
        "360 Aries 0"
      ],
      "constellational" : [
        "9 Aries 0",
        "0 Taurus 0",
        "3 Taurus 0", // Number 28
        "18 Taurus 0", // Number 1
        "29 Taurus 0",
        "10 Gemini 0",
        "24 Gemini 0",
        "9 Cancer 0",
        "20 Cancer 0",
        "7 Leo 0",
        "18 Leo 0",
        "28 Leo 0",
        "12 Virgo 0",
        "22 Virgo 0",
        "27 Virgo 0",
        "24 Libra 0",
        "4 Scorpio 0",
        "15 Scorpio 0",
        "3 Sagittarius 0",
        "10 Sagittarius 0",
        "24 Sagittarius 0",
        "13 Capricorn 0",
        "16 Capricorn 0",
        "4 Aquarius 0",
        "12 Aquarius 0",
        "23 Aquarius 0",
        "4 Pisces 0",
        "23 Pisces 0",
      ],
      "arabic" : [
        "void",
        "Al-Sharatain",
        "Al-Butain",
        "Al-Thuraiya",
        "Al-Dabaran",
        "Al-Haqa",
        "Al-Hana",
        "Al-Dhira",
        "Al-Nathrah",
        "Al-Tarf",
        "Al-Jabhah",
        "Al-Zubrah",
        "Al-Sarfah",
        "Al-Awwa",
        "Al-Simak",
        "Al-Ghafr",
        "Al-Zubana",
        "Al-Iklil",
        "Al-Qalb",
        "Al-Shaulah",
        "Al-Naaim",
        "Al-Baldah",
        "Sa’d al-Dhabih",
        "Sa’d Bula",
        "Sa’d al Suud",
        "Sa’d al-Akhbiyah",
        "Al Fargh al-Awwal",
        "Al Fargh al-Thani",
        "Batn al-Hut"
      ],
      "latin" : [
        "void",
        "Alnath",
        "Albotain",
        "Azoraya",
        "Aldebaran",
        "Almices",
        "Athaya",
        "Aldira",
        "Annathra",
        "Atarf",
        "Algebha",
        "Azobra",
        "Acarfa",
        "Alahue",
        "Azimech",
        "Algarfa",
        "Azubene",
        "Alichil",
        "Alcalb",
        "Exaula",
        "Nahaym",
        "Elbelda",
        "Caadaldeba",
        "Caaddebolach",
        "Caddacohot",
        "Caadalhacbia",
        "Almiquedam",
        "Algarf almuehar",
        "Arrexhe"
      ]
    }
  },
  "planet": {
    "name" : [
      "void",
      "Sun",
      "Moon",
      "Mars",
      "Mercury",
      "Jupiter",
      "Venus",
      "Saturn"
    ],
    "symbol" : [
      "void",
      "☉",
      "☽",
      "♂",
      "☿",
      "♃",
      "♀",
      "♄"
    ],
    "day" : [
      "void",
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"
    ]
  },
  "zodiac": {
    "name" : [
      "void",
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpio",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces"
    ],
    "symbol" : [
      "void",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓"
    ],
    "ruler" : [
      "void",
      3,
      6,
      4,
      2,
      1,
      4,
      6,
      3,
      5,
      7,
      7,
      5
    ]
  },
  "decan" : {
    "greek" : [ // Le Livré Sacre sur les Décans
      "void",
      "Chenlachori",
      "Chontaret",
      "Siket",
      "Soou",
      "Aron",
      "Rhomenos",
      "Xocha",
      "Ouari",
      "Pepisoth",
      "Sotheir",
      "Ouphisit",
      "Chnouphos",
      "Chnoumos",
      "Ipi",
      "Phatiti",
      "Athoum",
      "Brysous",
      "Amphatham",
      "Sphoukou",
      "Nephthimes",
      "Phou",
      "Name",
      "Oustichos",
      "Aphebis",
      "Sebos",
      "Teuchmos",
      "Chthisar",
      "Tair",
      "Epitek",
      "Epichnaus",
      "Isi",
      "Sosomo",
      "Chonoumous",
      "Tetimo",
      "Sopphi",
      "Syro"
    ],
    "latin" : [ // Liber Hermetis
      "void",
      "Aulathamas",
      "Sabaoth",
      "Disornafais",
      "Jaus",
      "Sarnotois",
      "Erchmubris",
      "Manuchos",
      "Samurois",
      "Azuel",
      "Seneptois",
      "Somachalmais",
      "Charmine",
      "Zaloias",
      "Zachor",
      "Frich",
      "Zamendres",
      "Magois",
      "Michulais",
      "Psineus",
      "Chusthisis",
      "Psamiatois",
      "Necbeuos",
      "Turmantis",
      "Psermes",
      "Clinothois",
      "Thursois",
      "Renethis",
      "Renpsois",
      "Manethois",
      "Marcois",
      "Ularis",
      "Luxois",
      "Crauxes",
      "Fambais",
      "Flugmois",
      "Piatris"
    ],
    "egyptian" : [ // Bennu Society
      "void",
      "Qd",
      "Sasa Qd",
      "A'rt",
      "Khaw",
      "Msdjr Sah",
      "Rmn Khr Sah",
      "A'sah",
      "Sah",
      "Spdt",
      "Dpa'knmwt",
      "Knmt",
      "Khr Khp Knmwt",
      "Hadjat",
      "Phwy Djat",
      "Thmat Hrt",
      "Thmat Khrt",
      "Wasthy",
      "Bakathy",
      "Dpa'Khntt",
      "Khntt Hrt",
      "Khntt Khrt",
      "Thmsn Khntt",
      "Sapt Khnnw",
      "Hr Ab Wya",
      "Shsmw",
      "Knmw",
      "Smdt",
      "Dpa'smdt",
      "Srt",
      "Sasa Srt",
      "Khr Khpt Srt",
      "Khw Khw",
      "Ba Ba",
      "Khnt Hrw",
      "Hr Ab Khtw",
      "Khnt Khrw"
    ],
    "ruler" : [
      "void",
      3, 1, 6,
      4, 2, 7,
      5, 3, 1,
      6, 4, 2,
      7, 5, 3,
      1, 6, 4,
      2, 7, 5,
      3, 1, 6,
      4, 2, 7,
      5, 3, 1,
      6, 4, 2,
      7, 5, 3
    ]
  }
};
